### ISSUE TITLE
Main Home screen

### ISSUE THREAD

**Issue by vvelazquezc** [Musikverein/musikverein-project#42]
- [x] #2 Basic home screen
- [x] #5 Section "popular playlist" in Home Screen
- [x] #27 Section "Popular Artist" in home screen
- [x] #31 Section "Playlist followed" in Home Screen
