### ISSUE TITLE
Account management

### ISSUE THREAD

**Issue by vvelazquezc** [Musikverein/musikverein-project#43]
User Story
- [x] #10 Viewing user information
- [x] #11 Editing user information
- [x] #17 Changing user password
