### ISSUE TITLE
Publication, display and management of songs

### ISSUE THREAD

**Issue by vvelazquezc** [Musikverein/musikverein-project#46]
User Sroty 
- [x] #12 Song upload
- [x] #16 Showing "My songs"
- [x] #18 Like a song
- [x] #28 Like a song within the song information dialog
- [x] #30 Song edit option within song info dialog
- [x] #33 Delete song button from a playlist from song info dialog
