### ISSUE TITLE
Publishing, viewing and managing playlists

### ISSUE THREAD

**Issue by joserra-15** [Musikverein/musikverein-project#50]
- [x] Playlists list #3
- [x] Manually playlist order #9
- [x] Playlist creation #13
- [x] Show playlist #14
- [x] Follow a playlist in playlists view #15
- [x] Privacity change in playlist view #20
- [x] Add song to a playlist inside this playlist view #25
- [x] "Options" menu, inside of the palylist #29
